package Exchange;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class UI extends javax.swing.JFrame {

    public UI() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("C:/Users/Ayoze/Desktop/imgCurrency/logo.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jTextFieldCantidad = new javax.swing.JTextField();
        jPanelCantidad = new javax.swing.JPanel();
        jLabelInstruccionesCantidad = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jPanelDivisas = new javax.swing.JPanel();
        jLabelInstrucciones = new javax.swing.JLabel();
        jLabelmOrigen = new javax.swing.JLabel();
        jTextFieldmOrigen = new javax.swing.JTextField();
        jLabelmFinal = new javax.swing.JLabel();
        jTextFieldmFinal = new javax.swing.JTextField();
        jTextResultado = new javax.swing.JTextField();
        jButtonConvertir = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(204, 153, 0));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));
        getContentPane().add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 100, -1));

        jPanelCantidad.setBackground(new java.awt.Color(204, 153, 0));

        jLabelInstruccionesCantidad.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabelInstruccionesCantidad.setText("Use \".\" para separar los decimales");
        jPanelCantidad.add(jLabelInstruccionesCantidad);

        jLabelCantidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidad.setText("Introduzca cantidad a convertir: ");
        jPanelCantidad.add(jLabelCantidad);

        getContentPane().add(jPanelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 310, 50));

        jPanelDivisas.setBackground(new java.awt.Color(204, 153, 0));

        jLabelInstrucciones.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabelInstrucciones.setText("Use \"EUR\" para euros o \"USD\" para dólares");
        jPanelDivisas.add(jLabelInstrucciones);

        jLabelmOrigen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelmOrigen.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmOrigen.setText("Introduzca divisa origen: ");
        jPanelDivisas.add(jLabelmOrigen);

        jTextFieldmOrigen.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jTextFieldmOrigen.setPreferredSize(new java.awt.Dimension(45, 20));
        jPanelDivisas.add(jTextFieldmOrigen);

        jLabelmFinal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelmFinal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmFinal.setText("Introduzca divisa final: ");
        jPanelDivisas.add(jLabelmFinal);

        jTextFieldmFinal.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jTextFieldmFinal.setPreferredSize(new java.awt.Dimension(45, 20));
        jPanelDivisas.add(jTextFieldmFinal);

        getContentPane().add(jPanelDivisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 310, 80));

        jTextResultado.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextResultado.setForeground(new java.awt.Color(204, 153, 0));
        jTextResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 170, 50));

        jButtonConvertir.setBackground(new java.awt.Color(153, 153, 153));
        jButtonConvertir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonConvertir.setForeground(new java.awt.Color(204, 153, 0));
        jButtonConvertir.setText("CONVERTIR");
        jButtonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextResultadoActionPerformed

    private void jButtonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertirActionPerformed
        String mO = null, mF = null, sO = null, sF = null;
        double amount = 0, rate = 0, result;
        
        if(!jTextFieldCantidad.getText().equals("") && Double.valueOf(jTextFieldCantidad.getText()) >= 0) {
            try {
                amount = Double.valueOf(jTextFieldCantidad.getText());
            } catch (NumberFormatException e) {
                System.err.println("Número positivo esperado, use el formato indicado");
            }
        }
        
        switch (jTextFieldmOrigen.getText()) {
            case "EUR":
            case "eur":
                mO = "EUR";
                sO = "€";
                switch (jTextFieldmFinal.getText()) {
                    case "EUR":
                    case "eur":
                        mF = "EUR";
                        sF = "€";
                        break;
                    case "USD":
                    case "usd":
                        mF = "USD";
                        sF = "$";
                        break;
                    default:
                        System.err.println("Divisa final incorrecta, use el formato indicado");
                        break;
                }
            break;
            case "USD":
            case "usd":
                mO = "USD";
                sO = "$";
                switch (jTextFieldmFinal.getText()) {
                    case "EUR":
                    case "eur":
                        mF = "EUR";
                        sF = "€";
                        break;
                    case "USD":
                    case "usd":
                        mF = "USD";
                        sF = "$";
                        break;
                    default:
                        System.err.println("Divisa final incorrecta, use el formato indicado");
                        break;
                }
            break;
            default:
            System.err.println("Divisa origen incorrecta, use el formato indicado");
            break;
        }
        
        CurrencyRate cRate = new CurrencyRate(mO, mF);
        
        try {
            rate = cRate.rate(mO, mF);
        } catch (IOException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        result = amount * rate;
        result =  Math.round(result * Math.pow(10, 2)) / Math.pow(10, 2);
        
        jTextResultado.setText(amount + sO + "\n equivalen a \n" + result + sF);
    }//GEN-LAST:event_jButtonConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConvertir;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelInstrucciones;
    private javax.swing.JLabel jLabelInstruccionesCantidad;
    private javax.swing.JLabel jLabelmFinal;
    private javax.swing.JLabel jLabelmOrigen;
    private javax.swing.JPanel jPanelCantidad;
    private javax.swing.JPanel jPanelDivisas;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldmFinal;
    private javax.swing.JTextField jTextFieldmOrigen;
    private javax.swing.JTextField jTextResultado;
    // End of variables declaration//GEN-END:variables
}
